//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMovies
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int movieID { get; set; }
        public string name { get; set; }
        public string director { get; set; }
        public Nullable<bool> seen { get; set; }
        public Nullable<byte> rating { get; set; }
        public string poster { get; set; }
        public Nullable<System.DateTime> watchingDate { get; set; }
        public string localization { get; set; }
        public string genre { get; set; }
    }
}
